# Generated by Django 4.2.30 on 2026-04-11 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель')),
                ('instrument', models.CharField(choices=[('guitar', 'Гитара'), ('electric', 'Электрогитара'), ('bass', 'Бас-гитара'), ('drums', 'Барабаны')], max_length=20)),
                ('tempo', models.PositiveIntegerField(default=120)),
                ('time_signature_top', models.PositiveSmallIntegerField(default=4)),
                ('time_signature_bottom', models.PositiveSmallIntegerField(default=4)),
                ('tuning', models.JSONField(blank=True, default=list, help_text='Настройка струн, напр. ["E4","B3","G3","D3","A2","E2"]')),
                ('data', models.JSONField(default=dict, help_text='Данные табулатуры (такты, ноты, техники)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Табулатура',
                'verbose_name_plural': 'Табулатуры',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TabShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_shares', to=settings.AUTH_USER_MODEL)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='tabs.tab')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отправка таба',
                'verbose_name_plural': 'Отправки табов',
                'ordering': ['-created_at'],
                'unique_together': {('tab', 'from_user', 'to_user')},
            },
        ),
    ]
